Add release workflows
GeoWerkstatt/interlis-model-repository pull request #6
Opened 2023-02-02 10:15 UTC by Philippluca

2023-02-02 10:51 UTC, danjov approved these changes
LGTM

2023-02-02 12:39 UTC, flenny requested changes
Sorry hab erst jetzt gechecked, dass es zwei PR's sind 🙈 Einzelne Aspekte müsstets du also noch in https://github.com/GeoWerkstatt/interlis-model-repository/pull/5 einarbeiten... sorry 😅

2023-02-02 12:39 UTC, flenny commented on .github/workflows/pre-release.yml
> +      - name: Create GitHub pre-release
PP: pre-release via [GitHub API](https://cli.github.com/manual/gh_api) erstellen (Ist in GH Actions bereits installiert/vorkonfiguriert). Damit könnten wir eine Abhängigkeit zu einer 3rd Party GH Action loswerden.

Pseudo-Code
```yml
- name: Create GitHub pre-release
        run: |
          gh api \
            --method POST \
            --header "Accept: application/vnd.github+json" \
            /repos/${GITHUB_REPOSITORY}/releases \
            -f tag_name='v${{ env.VERSION }}' \
            -f target_commitish='main' \
            -f name='${{ env.VERSION }}' \
            -F prerelease=true \
```

2023-02-02 12:39 UTC, flenny commented on repository-validator/ili2c-repository-check.sh
> +# Execute ilivalidator/ili2gpkg with the given options
REQ: Kommentar anpassen

2023-02-02 12:39 UTC, flenny commented on repository-validator/docker-entrypoint.sh
> +# Download and configure ilivalidator and optional ili2pgkg
REQ: Kommentar anpassen
PP: Funktion direkt inlinen, da nur einmal verwendet.

2023-02-02 12:39 UTC, flenny commented on README.md
> +| `ILITOOLS_HOME_DIR` | Override where the ili2c will be downloaded to. |
Q/REQ: Mir ist der Sinn dieser ENV's nicht klar. Es ist völlig irrelevant von wo die Daten im Container gelesen, nach wo geschrieben und wohin das ili2c executable kopiert wird. Besser dokumentieren wie die Docker-Volumes gemountet werden müssen.
```yml
volumes:
      - ./input:/input
      - ./output:/output
```

2023-02-02 12:39 UTC, flenny commented on repository-validator/ili2c-repository-check.sh
> +proxy_host=${proxy_host#*://} # remove protocol
REQ: Unbedingt dokumentieren wie die `$PROXY` ENV aussehen muss (inkl. Port und Protokoll), sonnst bricht das Skript an dieser stelle.

```yml
 #   - PROXY=http://USER:PASSWORD@example.com:8080
    #     Optional, Configuring proxy settings for all apps in the container
    #     Protocol (e.g. http://) and port (e.g. 8080) is mandatory in order do be able
    #     to parse values properly
    #     examples: - http://example.com:8080
    #               - https://host.example.com:443
    #               - http://10.10.5.68:5698
    #               - https://USER:PASSWORD@10.10.5.68:8443
```

2023-02-02 12:39 UTC, flenny commented on repository-validator/ili2c-repository-check.sh
> +[[ $ILIVALIDATOR_ENABLE_TRACE = true ]] && options+=" --trace"
REQ: Dokumentieren und besserer Namen wählen.

2023-02-02 12:39 UTC, flenny commented on repository/Dockerfile
> +ARG ENABLED_MODULES=fancyindex
PP: ENV verwenden

2023-02-02 12:39 UTC, flenny commented on README.md
> +| `ILI2C_VALIDATION_REPOSITORY` | Specify corresponding online repositories to check for dependant Models. Default: `http://models.interlis.ch/` |
PP: Beispiel für mehrere Repositories machen. Allenfalls ENV unbenennen -> repositories

2023-02-02 12:39 UTC, flenny commented on repository-validator/ili2c-repository-check.sh
> +[[ -n $ILIVALIDATOR_MODEL_DIR ]] && options+=" --modeldir $ILIVALIDATOR_MODEL_DIR"
REQ/Q: Das muss weg, oder? Resp. nach  `--check-repo-ilis $ILI2C_INPUT_DIR` umbiegen.

2023-02-02 12:39 UTC, flenny commented on repository-validator/docker-entrypoint.sh
> +ilivalidator trace messages:      $([[ $ILIVALIDATOR_ENABLE_TRACE = true ]] && echo enabled || echo disabled)
REQ: Info anpassen

2023-02-02 12:39 UTC, flenny commented on repository-validator/docker-entrypoint.sh
> +http proxy exceptions:            $([[ -n $NO_PROXY ]] && echo $NO_PROXY || echo undefined)
REQ: ENV `$NO_PROXY `Dokumentieren oder info weglassen.

2023-02-02 12:48 UTC, flenny requested changes

2023-02-02 12:48 UTC, flenny commented on docker-compose.yml
> +      - validated-repository:/data:ro
Q: Stimmt das `/data`? Ich seh im Container kein solcher Ordner.

2023-02-02 12:48 UTC, flenny commented on .github/workflows/pre-release.yml
> +          context: [repository, repository-validator]
REQ: Image names im README.md dokumentieren, resp. bestehende Namen mit dem neuen anpassen.

2023-02-02 12:48 UTC, flenny commented on repository-validator/ili2c-repository-check.sh
> +$JAVA_HOME/bin/java -jar $ILITOOLS_HOME_DIR/ili2c/$ILI2C_VERSION/ili2c.jar $options --check-repo-ilis $ILI2C_INPUT_DIR
Q: Ist `--check-repo-ilis` an dieser Stelle korrekt? Zumindes in der [Doku](https://github.com/claeis/ili2c/blob/master/doc/ili2c.rst) konnte ich nichts dazu finden.

2023-02-02 12:55 UTC, flenny commented on repository-validator/docker-entrypoint.sh
> +export ILI2C_MODEL_DIR="$ILI2C_INPUT_DIR;${ILI2C_VALIDATION_REPOSITORY:-http://models.interlis.ch/}"
Q: Wo wird `$ILI2C_MODEL_DIR` verwendet?

2023-02-03 11:02 UTC, Philippluca commented on repository-validator/docker-entrypoint.sh
> +export ILI2C_MODEL_DIR="$ILI2C_INPUT_DIR;${ILI2C_VALIDATION_REPOSITORY:-http://models.interlis.ch/}"
Wird nicht mehr verwendet. Tatsächlich brauch man die option `--modeldir` nicht mehr wenn `--check-repo-ilis` verwendet wird.

2023-02-03 11:02 UTC, Philippluca commented on repository-validator/ili2c-repository-check.sh
> +$JAVA_HOME/bin/java -jar $ILITOOLS_HOME_DIR/ili2c/$ILI2C_VERSION/ili2c.jar $options --check-repo-ilis $ILI2C_INPUT_DIR
Ist korrekt so: https://github.com/claeis/ili2c/issues/81

2023-02-03 11:04 UTC, Philippluca commented on docker-compose.yml
> +      - validated-repository:/data:ro
Ja: Es wird in `default.conf.template` entsprechend angezogen.

2023-02-03 11:06 UTC, Philippluca commented on README.md
> +| `ILI2C_VALIDATION_REPOSITORY` | Specify corresponding online repositories to check for dependant Models. Default: `http://models.interlis.ch/` |
Gestrichen. https://github.com/GeoWerkstatt/interlis-model-repository/pull/6#discussion_r1095676889

2023-02-03 11:10 UTC, Philippluca commented on .github/workflows/pre-release.yml
> +      - name: Create GitHub pre-release
Ich werde dies in einem separaten PR abhanden, da es hier bereits so getestet wurde und funktioniert.
Issue: https://github.com/GeoWerkstatt/interlis-model-repository/issues/7

2023-02-03 11:57 UTC, flenny approved these changes

2023-02-03 12:16 UTC, merged